# https://taskfile.dev

version: '3'

dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

tasks:
  aider:
    desc: launches AI coding tool aider
    cmds:
      - aider --model $LLM_MODEL/$MODEL_VERBOSE --api-key $LLM_MODEL=$API_KEY
  nvim_dev:
    desc: Load the AutoSaveFile.nvim plugin in your environment during development
    cmds:
      - API_KEY=$API_KEY nvim --clean -u dev_config/init.lua
  nvim_dev_en:
    cmds:
      - API_KEY=$API_KEY LANG=en_US.UTF-8 nvim --clean -u dev_config/init.lua
  nvim_dev_zh:
    cmds:
      - API_KEY=$API_KEY LANG=zh_CN.UTF-8 nvim --clean -u dev_config/init.lua
  nvim_dev_ja:
    cmds:
      - API_KEY=$API_KEY LANG=ja_JP.UTF-8 nvim --clean -u dev_config/init.lua
